
services:
  db:
    image: postgres:14
    container_name: postgres-autosave
    environment:
      POSTGRES_USER: krishna
      POSTGRES_PASSWORD: 458336
      POSTGRES_DB: autosave_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
